### ISSUE TITLE
Histogram that ignores black/white

### ISSUE THREAD

**Issue by howff** [pytroll/trollimage#1]
Is it possible to modify the histogram function so that it ignores black and white (or more generally some particular range or set of ranges). The use case is geostationary satellite images of the earth where the view into space around the earth is either black or white and makes up a substantial percent of the pixels which should not be included in the binning. Thanks

**Comment by mraspaud** [comment]
The way we usually do it is to use masked arrays for the data, with space pixels masked. That way the histogram function should work as expected.
