### ISSUE TITLE
Add "overviews" to save options

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollimage#27]
In GeoTIFF files (and maybe other formats, too) it is possible to embed lower resolution versions of the image within the same file. These are called "overviews" in rasterio documentation. The overviews speed up the processing significantly in WMS systems.

I added this as a quick test to trollflow-sat (https://github.com/pytroll/trollflow-sat/blob/feature-save-overviews/trollflow_sat/utils.py#L289), but the logical place would be in trollimage.

After this is implemented, we could add `'overviews'` to `satpy.writers.geotiff.GDAL_OPTIONS` tuple so that the option would pass to `trollimage`.

**Comment by djhoese** [comment]
Just a side comment: I think NinJo TIFFs require these "overview" images to work properly with NinJo.

**Comment by djhoese** [comment]
Implemented by #44. Reopen if you don't think it works the way you want. @mraspaud do we have an example in the docs for this?
