### ISSUE TITLE
ReadTheDoc page buildts not up to date

### ISSUE THREAD

**Issue by adybbroe** [pytroll/trollimage#30]
#### Problem description

On RTD I see two sections called _Simple images_? One is empty.

Also, RTD needs to be set up to build against master and not develop. I guess develop branch is gone now, isn't it? It should at least.

**Comment by adybbroe** [comment]
Ok, thx @mraspaud and @djhoese Now master is being build on update, and develop is removed.
Still remains the thing about the two "Simple images" sections

**Comment by djhoese** [comment]
As mentioned on xarray the two simple images sections were due to the xrimage module having an importerror because rasterio is not available. I'm working on this now, including renaming the section.
