### ISSUE TITLE
Add alpha channel to Colormaps

### ISSUE THREAD

**Issue by goodsonr** [pytroll/trollimage#5]
New versions of trollmage should allow and use an alpha channel as part of the Colormap.  Current color maps allow (r,g,b).  It is suggested that this be extended to (r,g,b,a) and the alpha channel would be used when colorizing and palletizing imagery.

**Comment by djhoese** [comment]
@goodsonr is this fixed now with your recent PR(s) #40?

**Comment by goodsonr** [comment]
for completeness (since close) .. yes
