### ISSUE TITLE
JPEG does not support transparency, thus the user needs to specify a fill-value

### ISSUE THREAD

**Issue by adybbroe** [pytroll/trollimage#6]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from satpy.scene import Scene
from satpy.utils import debug_on
debug_on()
from glob import glob

FILES = glob("/data/lang/satellit/geo/hrit/201610/20161019_12/H-000*__")
scn = Scene(reader="hrit_msg", filenames=FILES)
scn.load(['IR_108'])
scn.save_dataset('IR_108', './test_bw.jpg')
```

#### Problem description
JPEG does not support transparency, thus the user needs to specify a fill-value. But if the user does not remember to do so, as he/she may not actually know that what is about to be stored is an image with an alpha channel. The default in satpy is to have fill_value=None, and then the above code will result in the error listed below.

In the case of Satpy it is sufficient to do:
```
scn.save_dataset('IR_108', './test_bw.jpg', fill_value=0)
```

But, would be helpful with a more graceful error handling!

#### Actual Result, Traceback if applicable

```
[DEBUG: 2017-12-20 11:32:32 : satpy.writers.simple_image] Saving to image: ./test_bw.jpg
Traceback (most recent call last):
  File "issues_satpy_saveimage.py", line 38, in <module>
    scn.save_dataset('IR_108', './test_bw.jpg')
  File "/home/a000680/usr/src/satpy/satpy/scene.py", line 625, in save_dataset
    overlay=overlay, **kwargs)
  File "/home/a000680/usr/src/satpy/satpy/writers/__init__.py", line 365, in save_dataset
    self.save_image(img, filename=filename, **kwargs)
  File "/home/a000680/usr/src/satpy/satpy/writers/simple_image.py", line 42, in save_image
    img.save(filename)
  File "/home/a000680/usr/src/trollimage/trollimage/image.py", line 362, in save
    thumbnail_name, thumbnail_size)
  File "/home/a000680/usr/src/trollimage/trollimage/image.py", line 389, in pil_save
    img.save(filename, fformat, **params)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1477, in save
    save_handler(self, fp, filename)
  File "/usr/lib64/python2.7/site-packages/PIL/JpegImagePlugin.py", line 450, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode LA as JPEG
```

#### Versions of Python, package at hand and relevant dependencies

Python 2.7.5, Satpy 0.7.6

**Comment by davidh-ssec** [comment]
The fill value is the equivalent of setting masked values to a certain color right? Could we just have the JPEG format default to black?

**Comment by adybbroe** [comment]
Yes, that is what my PR does.
Right?

**Comment by davidh-ssec** [comment]
You never linked to #7. I didn't know there was a PR.

**Comment by djhoese** [comment]
This has been handled in satpy and I think it is acceptable to expect the user to know how to handle the format they are writing to.
