### ISSUE TITLE
Add support for Cloud Optimized GeoTIFF

### ISSUE THREAD

**Issue by howff** [pytroll/trollimage#93]
It;s possible to write a valid COG using the options `tiled=True, blockxsize=512, blockysize=512`

COG files are supposed to have overviews which go down to a size less than 512.

However, when trying to add overview using the options `overviews=[2, 4, 8, 16], overviews_resampling='cubic', copy_src_overview=True` the resulting file has the TIFF IFD out of order and the file fails validation (see the GDAL utility `validate_cloud_optimized_geotiff.py`). Also, the amount of overviews might not match the image size.

GDAL since version 3.1 now has a COG driver which takes care of the intricacies like this.

Suggestion: use the COG driver when writing GeoTIFF.  Even for people who don't specifically need COG files, the output file, being tiled, is usually smaller than a strip-compressed image anyway. Although they might not want/need the additional overviews. Alternatively detect filename `.cog.tif` and switch to the COG driver?

**Comment by djhoese** [comment]
Thanks for the issue. This is an important thing to bring up. My feelings and some concerns:

1. > COG files are supposed to have overviews
   They can, but they don't have to. Or at least it wasn't a requirement in the past.
2. >  the resulting file has the TIFF IFD out of order and the file fails validation
   Do you have an example script where you create fake data and it fails validation with these arguments?
3. > Also, the amount of overviews might not match the image size.
   What do you mean by this?
4. > GDAL since version 3.1 now has a COG driver which takes care of the intricacies like this.
   I'm torn on this. I seem to remember the COG driver not doing much extra but it seems based on the documentation (https://gdal.org/drivers/raster/cog.html#cog-cloud-optimized-geotiff-generator) that is also adds the overviews for you. That would be nice.
5. The `.cog.tif` as far as I know isn't standard so I wouldn't want to rely on this.
6. We have talked about enabling tiling by default but it always seems to be one of those "wait, didn't we do that already". I wouldn't want to enable overviews by default though.

**Comment by djhoese** [comment]
Oh also, we should really switch to using `rioxarray` to do this for the XRImage. It includes handling of writing with dask distributed which is a major limitation of what we do now.

**Comment by howff** [comment]
1. I think you misquoted me. As I said above, it validates without an overview. The point I was making relates to this part of the COG driver spec "Overviews until the maximum dimension of the smallest overview level is lower than 512 pixels". That means the number and size of overviews depends on the size of the original image, so you can't just do `[2,4,8,16]`.

2. I don't have fake date, just real data ;-)  The validation errors you get from adding overviews in satpy are:
```
 - The offset of the first block of overview of index 2 should be after the one of the overview of index 3
 - The offset of the first block of overview of index 1 should be after the one of the overview of index 2
 - The offset of the first block of overview of index 0 should be after the one of the overview of index 1
 - The offset of the first block of the main resolution image should be after the one of the overview of index 3
```

3. see above

4.  Yes, the COG driver does quite a few things including automatic overviews :)
 
5. I agree. The driver is already chosen based on the filename, so if you wanted the COG driver to be optional then this might be one easy way of achieving that. There are much better options - I would be happy to add it the PR if someone suggests one.

**Comment by djhoese** [comment]
1. RE misquoting: How so? I copied and pasted what you said. The current geotiff writing is supposed to handle the "down to 512" business as we use the function from rasterio and their implementation was ported from gdal_translate I think. See https://github.com/pytroll/trollimage/blob/5aeef5a2534442434cb00b0a9e091bf72a222130/trollimage/xrimage.py#L211-L217
2. Interesting. We are diong things in the same way the rasterio docs suggest https://rasterio.readthedocs.io/en/latest/topics/overviews.html so this must just be invalid COG-wise.

What if we choose the COG driver if the user specifies the tile keyword argument and then we adjust the `blockxsize/blockysize` options to be `blocksize` (or whatever it is supposed to be called) and dealing with the other options if needed (overviews). Would that be possible? My biggest worry based on the warnings you showed originally is the photometric option as there may be edge cases where XRImage expects to be able to store non-RGB or non-L images in a COG-like geotiff. This is an edge case, but still something we should be aware of.

@mraspaud is on vacation this week, but I know he had looked a little bit into switching to rioxarray. I'm not saying it has to be done in your PR, but if we can avoid future complexities by expecting to switch to rioxarray in the future that would be good.

**Comment by howff** [comment]
The refactoring can be a different PR (I wouldn't know what to do anyway!).

Instead of using COG if tiled=True I've chosen to use COG if overlays=[], because you might want a tiled image without overviews (it makes the file smaller), and by saying overviews=[] you are asking for some automatic creation of overviews which is exactly what the COG driver gives you, but better.

I've also fiddled with format_kwargs to prevent the warnings (and use LEVEL instead of ZLEVEL). I'm not sure if the use of pop() here breaks something outside the function.

**Comment by djhoese** [comment]
> Instead of using COG if tiled=True I've chosen to use COG if overlays=[], because you might want a tiled image without overviews (it makes the file smaller), and by saying overviews=[] you are asking for some automatic creation of overviews which is exactly what the COG driver gives you, but better.

Can't the COG driver do tiled geotiffs with no overviews?

**Comment by howff** [comment]
The COG driver has lots of options, one of which is no overviews.

If you don't want `overviews=[]` to trigger COG format then how about an additional argument to `save_dataset` such as `cloud_optimized=True` ?  This can be implemented simply in `satpy/writers/geotiff.py` by adding that keyword to `GDAL_OPTIONS`. We could also add other keywords there for the other options which COG supports. Let me know what you prefer.

**Comment by djhoese** [comment]
So I originally suggested that COG be used if `tiled` was specified, would that still be possible? Then you could map the `overviews` keyword argument to either None (no overviews), `[]` for AUTO, and if the user specifies overviews...oh I see. COG doesn't let you customize the overview sizes.

I'm not sure we need an extra keyword argument, but I'm willing to admit that I might be missing some complexity here. I'm ok with `[]` triggering the COG driver, but it seems odd that anything other than `[]` will not trigger COG. I'm not sure what the right solution is right now. I'll sleep on it.

**Comment by howff** [comment]
I could change it to trigger COG if `tiled` is set if you prefer that. The COG options for overviews can be AUTO / IGNORE_EXISTING / FORCE_USE_EXISTING / NONE so you can't control the number of levels but you can pass in overviews you've already created which is just as good/better. I would have to check whether it would properly fix the TIFF IFD if you pass in your own overviews though.

I still think that if you say `overviews=[]` you are asking for them to be created automatically, and the COG driver is the best way that we have for creating overviews that are compatible. If you want to be in control of overview creation you can pass your own overviews into the COG driver (at the possible expense of compatibility but that might not be important to that user).

Having looked at the range of creation options for each driver, it's odd that COG isn't simply an easy way of calling the GTiff driver with sane options, it does appear to have some differences. Given that we don't know how the users might want to create their geotiffs (they might want a GTiff option that isn't exposed by COG), would it be safer to make the use of the COG driver more explicit (i.e. as a separate option `cloud_optimized=True`) ?  On the other hand if we are trying to make geotiff creation easy to use then hiding some of these options is not a bad thing.

Interestingly the COG driver also has the ability to perform a reprojection step!

| Creation option       | COG                                | GTiff                                  |
|-----------------------|------------------------------------|----------------------------------------|
| blocksize             | only blocksize                     | blockxsize, blockysize are independent |
| compress              | Y                                  | Y                                      |
| level                 | level is for all compression types | zlevel, zstd_level, webp_level         |
| max_z_error           | Y                                  | Y                                      |
| quality               | Y                                  | jpeg_quality                           |
| num_threads           | Y                                  | Y                                      |
| predictor             | Y                                  | Y                                      |
| bigtiff               | Y                                  | Y                                      |
| resampling            | Y                                  |                                        |
| overview_resampling   | Y                                  |                                        |
| warp_resampling       | Y                                  |                                        |
| overviews             | Y                                  |                                        |
| overview_compress     | Y                                  |                                        |
| overview_quality      | Y                                  |                                        |
| overview_predictor    | Y                                  |                                        |
| geotiff_version       | Y                                  | Y                                      |
| sparse_ok             | Y                                  | Y                                      |
| tfw                   |                                    | Y                                      |
| rpb                   |                                    | Y                                      |
| rpctxt                |                                    | Y                                      |
| interleave            | implicit                           | Y                                      |
| tiled                 | implicit                           | Y                                      |
| nbits                 |                                    | Y                                      |
| discard_lsb           |                                    | Y                                      |
| jpeg_tables_mode      | implicit                           | Y                                      |
| webp_*                |                                    | Y                                      |
| jxl_*                 |                                    | Y                                      |
| photometric           | implicit/automatic                 | Y                                      |
| alpha                 |                                    | Y                                      |
| profile               |                                    | Y                                      |
| pixeltype             |                                    | Y                                      |
| copy_src_overviews    | handled in overviews option        | Y                                      |
| geotiff_keys_flavor   |                                    | Y                                      |
| REPROJECTION OPTIONS: |                                    |                                        |
| tiling_scheme         | Y                                  |                                        |
| zoom_level_strategy   | Y                                  |                                        |
| target_srs            | Y                                  |                                        |
| res                   | Y                                  |                                        |
| extent                | Y                                  |                                        |
| aligned_levels        | Y                                  |                                        |
| add_alpha             | Y                                  |                                        |
|                       |                                    |                                        |

**Comment by mraspaud** [comment]
does nbits being empty for COG mean that you can only have 8 bits? Regarding photometric, does it support YCbCr that we are using in some cases?

**Comment by djhoese** [comment]
My vote is that COG is used if `tiled` is true and `overviews` is either `[]` (AUTO) or `None` (NONE). Or should `None` mean `FORCE_USE_EXISTING`? Or does `overviews` allow for a string value that gets passed directly to the COG driver. So the only case where COG would not be used when tiled is true is if `overviews` are explicitly specified.

I'm curious how these overviews work considering we're using dask and it only writes windows/chunks of data at a time.

**Comment by howff** [comment]
At the moment NBITS might only be supported by GTiff not COG (but the COG driver author is happy to extend the driver if necessary). Having said that, it does mention support for 12-bit JPEG in TIFF, so I may be wrong about NBITS.

It also supports YCbCr for JPEG, not sure about non-JPEG.

I've implemented djhoese's suggestion of using COG if both `tiled=True` and `overviews=[]`

If that combination is used by someone to write a TIFF which would not work with the COG driver then we can revisit this.

**Comment by gerritholl** [comment]
> My vote is that COG is used if `tiled` is true and `overviews` is either `[]` (AUTO) or `None` (NONE).

How would this affect existing users?  Does COG imply overviews are calculated automatically?  We are writing GeoTIFFs that are tiled, but do not contain overviews.  We are also passing both `blockxsize` and `blockysize`, which would be invalid for a COG?

It would seem that this change needs substantial testing to make sure that various cases either do not change existing behaviour, or that a change in existing behaviour is clearly documented, including a note on how to retain the old behaviour.

**Comment by djhoese** [comment]
@gerritholl This is a very good point. There are so many options that a user might want to specify that may be incompatible with COG. So I guess we either:

1. Go back to @howff's idea of a special keyword argument (or allow for `driver=` to be passed if not possible already) to explicitly request the COG driver.
2. Fix the various warnings/failures of our current files so they are considered valid COG files until we completely switch to rioxarray. This assumes that rioxarray makes these decisions for us about COG versus not.

**Comment by howff** [comment]
COG's tiles are square so I've translated `blockxsize` to `blocksize` and ignored `blockysize`. If they differ (non-square) then the COG driver won't be used.

I decided against using COG if `overviews=None` because you can produce a valid COG-file without the COG driver anyway, and because the big advantage to the COG driver is that it produces overviews correctly. Hence it's only used if `overviews=[] and tiled=True`

It's definitely possible that some esoteric use of the geotiff format might be affected (non-RGB, 18-bit, band-interleaved or something) so we can 
* keep this proposal and document it, or
* add an additional keyword such as `cloud_optimized=True` or
* allow `fformat=COG` (or `driver=`?). At the moment this doesn't work because `satpy/writers/geotiff.py` has hard-coded `fformat='tif'` but we can put some logic into there which allows fformat to be passed on?

**Comment by djhoese** [comment]
:thinking: I guess limiting it to only work in one specific case (auto overviews) makes sense and shouldn't break any other cases (or at least not too many). I guess my biggest question/curiosity is why our overviews and even the original full resolution image data is producing warnings when validated as a COG. Would something simple like reversing the order of the overviews list make this pass? Or is the main problem that we generate overviews after the original geotiff was already created? I guess what I'm saying is that it is too bad that we thought we were making COG files before and turns out they weren't completely valid.

I like the idea of having full control/use of the COG driver. I do think we could fix our overview generation with the existing code, but the handling of compressed data as described in the COG driver documentation sounds interesting and like something we don't want to handle ourselves in trollimage. @howff any feelings about this as this might make `NONE` overviews a good use case for the COG driver?

I think the keyword argument should be `driver=` and leave `fformat` as is...right?

**Comment by howff** [comment]
I've removed the code which tries to guess when to use the COG driver (there's no chance of it breaking anything now).

I've added a `driver='COG'` keyword here, and in `satpy/writers/geotiff.py` so if you want a Cloud-Optimised GeoTIFF then you have to specify the driver explicitly.
